config/routes.rb
require_relative 'routes/constraints'

Rails.application.routes.draw do

  devise_for :users, skip: [:sessions, :password]
  devise_scope :user do
    resources :sessions, only: [:new, :create] do
      collection do
        delete 'destroy', as: :destroy
        get 'password_reset', as: :password_reset
      end
    end
    resources :password_resets, only: [:new, :create, :edit, :update]
  end

  begin
    ActiveAdmin.routes(self)
  rescue ActiveAdmin::DatabaseHitDuringLoad => e
    puts "#{e.class} has occurred."
  end

  resources :inquiries, only: [:create]
  resources :groups, only: [:index]
  resources :monthly_report_comments, only: [:create, :edit, :update, :destroy]

  root to: 'root#index'

  resources :announcements, only: [:index]
  resources :user_profiles, only: [:show, :edit, :update]
  resources 'monthly_reports', except: :destroy, constraints: Constraints::PageCount do
    resources :monthly_report_likes, only: [:create, :destroy], as: 'likes'
    collection do
      get 'users/:user_id', action: :user, as: :user, user_id: /\d{,6}/, constraints: Constraints::TargetYear
      get :copy
    end
  end

  resources :articles, constraints: Constraints::PageCount do
    collection do
      get 'users/:user_id', action: :user, as: :user, user_id: /\d{,6}/
      get 'users/:user_id/drafts', action: :drafts, as: :drafts, user_id: /\d{,6}/
    end
  end
  resources :article_comments, only: [:create, :edit, :update, :destroy]

end

app/models/article.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string
#  body       :text
#  shipped_at :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, class_name: 'ArticleComment', dependent: :delete_all
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags

  validates :user, presence: true
  validates :title, length: { maximum: 100 }
  validates :body, length: { maximum: 5000 }

  with_options if: :shipped? do
    validates :title, presence: true
    validates :body, presence: true
    validates :article_tags, presence: true
  end

  scope :shipped, -> { where.not(shipped_at: nil) }
  scope :wip, -> { where(shipped_at: nil) }

  def ship
    self.shipped_at ||= Time.current
  end

  def shipped?
    shipped_at.present?
  end

  def browseable?(access_user)
    shipped? || user == access_user
  end

  def assign_relational_params(wip, tags)
    ship unless wip
    self.tags = tags
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :assign_placeholders, only: %i[new create edit update]
  before_action :assign_article, only: %i[edit update]

  def index
    references = [:user, { article_tags: :tag }]
    @articles = Article.includes(references).shipped.order(shipped_at: :desc).page params[:page]
  end

  def user
    @article_user = User.find(params[:user_id])
    @articles = @article_user.articles.includes(article_tags: :tag).shipped.order(shipped_at: :desc).page params[:page]
  end

  def drafts
    @articles = current_user.articles.includes(article_tags: :tag).wip.order(created_at: :desc).page params[:page]
  end

  def show
    @article = Article.includes(comments: :user).find(params[:id])
    raise(Forbidden, 'can not see wip articles of other users') unless @article.browseable?(current_user)
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = Article.new(permitted_params) do |article|
      article.user = current_user
      article.assign_relational_params(params[:wip], article_tags)
    end

    if @article.save
      redirect_to @article
    else
      flash_errors
      render :new
    end
  end

  def edit; end

  def update
    @article.assign_attributes(permitted_params)
    @article.assign_relational_params(params[:wip], article_tags)

    if @article.save
      redirect_to @article
    else
      flash_errors
      render :edit
    end
  end

  def destroy
    @article = current_user.articles.find(params[:id])

    if @article.destroy
      flash[:notice] = 'ノートを削除しました'
      redirect_to :articles
    else
      flash_errors
      render @article
    end
  end

  private

  def assign_article
    @article = current_user.articles.includes(article_tags: :tag).find(params[:id])
  end

  def permitted_params
    params.require(:article).permit(
      :title,
      :body,
    )
  end

  def flash_errors
    flash.now[:error] = @article.errors.full_messages
  end

  # TODO: https://github.com/hr-dash/hr-dash/pull/481/files#diff-ddd1a6250ecb975d0c309f9af262ff5eR37 のように置き換える
  def article_tags
    tags = params[:article][:article_tags]&.split(',')&.map do |name|
      tag = Tag.find_or_initialize_by_name_ignore_case(name.strip)
      tag.save ? tag : nil
    end&.compact

    tags || []
  end

  def assign_placeholders
    @placeholders = HelpText.placeholders(:article)
  end
end

app/views/articles/_comment.html.slim
.panel.panel-default id=("comment-#{comment.id}")
  .panel-heading.monthly-report-panel-header
    = link_to comment.user.name, user_profile_path(comment.user.user_profile), class: 'text-info'
    = ' さんが '
    = link_to comment.updated_at, article_path(comment.article_id, anchor: "comment-#{comment.id}"), class: 'text-info'
    = ' にコメント'
    - if comment.user == current_user
      .pull-right
        = content_tag :a, href: article_comment_path(comment), class: 'article_comment_destroy text-muted', 'data-method' => :delete, 'data-confirm' => 'コメントを削除してよろしいですか？'
          span.glyphicon.glyphicon-remove aria-hidden="true"
      .pull-right
        = content_tag :div, class: :article_comment_edit, style: 'cursor:pointer'
          span.glyphicon.glyphicon-pencil aria-hidden="true"
          = hidden_field_tag :comment_id, comment.id
  .panel-body
    .markdown-view
      textarea.hidden = comment.comment
      .markdown-body

app/views/articles/_form.html.slim
.page-content.well
  = form_for article, html: { class: 'form-horizontal' } do |f|
    .form-group
      = f.label :title, class: 'control-label col-sm-3'
      .col-sm-9
        = f.text_field :title, class: 'form-control', placeholder: placeholders[:title]
    .form-group
      = f.label :article_tags, class: 'control-label col-sm-3'
      .col-sm-9
        = f.hidden_field :article_tags, id: :article_tags_input, class: 'form-control'
        == render 'shared/tag_field', tags: article.article_tags.map(&:name), placeholder: placeholders[:tags], attr: 'article_tags'
    .form-group
      = f.label :body, class: 'control-label col-sm-3'
      .col-sm-9
        == render 'layouts/markdown_editor', rows: 40, attr: :body, form: f, placeholder: placeholders[:body]
    - if article.shipped_at
      = f.button 'Update （ノートを更新）', class: 'btn btn-lg btn-success btn-block'
    - else
      = f.button 'Save as WIP （下書き保存）', name: :wip, class: 'btn btn-lg btn-info btn-block'
      = f.button 'Ship（保存して公開）', class: 'btn btn-lg btn-success btn-block'

app/views/articles/_list.html.slim
a.list-group-item href=(article_path(article))
  = action_name == 'index' ? "#{article.user.name} " : ''
  br.visible-xs-block
  .visible-xs-inline
  small.article-shipped-at.text-muted.hidden-xs
    = "投稿日: #{article.shipped_at.strftime("%Y-%m-%d")}" unless action_name == 'drafts'
  - tags = article.article_tags.order('article_tags.id')
  .pull-right
    - tags.first(3).each do |tag|
      span.tag.label.label-success = "#{tag.name} "
    span.comments_count
      span.glyphicon.glyphicon-comment aria-hidden="true"
      span = article.comments_count
  br
  b = article.title

app/views/articles/drafts.html.slim
- provide :page_title, '下書き中のノート一覧'
.article-user
  .btn.btn-success.btn-sm
    = link_to '公開済みのノート一覧へ', user_articles_path(current_user)

  .page-content
    #article_index
      .list-group.article-index
        - if @articles.present?
          == render partial: 'list', collection: @articles, as: 'article'
        - else
          p 下書き中のノートはありません
    = paginate @articles

app/views/articles/edit.html.slim
- provide :page_title, 'ノート編集'

== render 'articles/form', article: @article, placeholders: @placeholders

app/views/articles/index.html.slim
- provide :page_title, "最新ノート一覧"
.page-content
  #article_index
    .list-group.article-index
      == render partial: 'list', collection: @articles, as: 'article'
  = paginate @articles

app/views/articles/new.html.slim
- provide :page_title, 'ノート登録'

== render 'articles/form', article: @article, placeholders: @placeholders

app/views/articles/show.html.slim
- provide :page_title, @article.title
.well.well-sm style='overflow:hidden'
  - if @article.tags.size > 0
    = render 'shared/tags', tags: @article.tags, prefix: :article
  - else
    = 'タグ未登録'
.panel-group.article-show
  .panel.panel-default
    - if current_user == @article.user
      .panel-heading
        .panel-title
          - if @article.shipped?
            span.label.label-success.article-status 公開済
          - else
            span.label.label-info.article-status 下書き
          .pull-right
             = link_to '', edit_article_path(@article),
               class: 'glyphicon glyphicon-pencil'
             a.glyphicon.glyphicon-remove data-toggle="modal" data-target="#article-confirm"
    .panel-body
      = render 'layouts/markdown_view', content: @article.body
  .pull-right.article-user-link
    = link_to "#{@article.user.name}さんのノート一覧へ", user_articles_path(@article.user.id)
.modal.fade#article-confirm
  .modal-dialog
    .modal-content
      .modal-header
        .modal-title ノートを削除
      .modal-body 本当にこのノートを削除しますか?
      .modal-footer
        = link_to 'はい', article_path(@article), method: :delete,
          class: 'btn btn-danger'
        button.btn.btn-default type="button" data-dismiss="modal" 閉じる
- if @article.shipped?
  h2 コメント
  == render partial: 'articles/comment', collection: @article.comments.order(:created_at), as: 'comment'

  == render 'shared/new_comment', comment: @article.comments.new, attr: 'new-comment', hidden: :article_id

app/views/articles/user.html.slim
- provide :page_title, (link_to "#{@article_user.name}さんのノート一覧", user_profile_path(@article_user.user_profile), class: 'text-profile-link')
.article-user
  - if @article_user == current_user
    .btn.btn-info.btn-sm
      = link_to '下書き中のノート一覧へ', drafts_articles_path(current_user)
  .page-content
    #article_index
      .list-group.article-index
        - if @articles.present?
          == render partial: 'list', collection: @articles, as: 'article'
        - else
          p 公開中のノートはありません
    = paginate @articles