config/routes.rb
require_relative 'routes/constraints'

Rails.application.routes.draw do

  devise_for :users, skip: [:sessions, :password]
  devise_scope :user do
    resources :sessions, only: [:new, :create] do
      collection do
        delete 'destroy', as: :destroy
        get 'password_reset', as: :password_reset
      end
    end
    resources :password_resets, only: [:new, :create, :edit, :update]
  end

  begin
    ActiveAdmin.routes(self)
  rescue ActiveAdmin::DatabaseHitDuringLoad => e
    puts "#{e.class} has occurred."
  end

  resources :inquiries, only: [:create]
  resources :groups, only: [:index]
  resources :monthly_report_comments, only: [:create, :edit, :update, :destroy]

  root to: 'root#index'

  resources :announcements, only: [:index]
  resources :user_profiles, only: [:show, :edit, :update]
  resources 'monthly_reports', except: :destroy, constraints: Constraints::PageCount do
    resources :monthly_report_likes, only: [:create, :destroy], as: 'likes'
    collection do
      get 'users/:user_id', action: :user, as: :user, user_id: /\d{,6}/, constraints: Constraints::TargetYear
      get :copy
    end
  end

  resources :articles, constraints: Constraints::PageCount do
    collection do
      get 'users/:user_id', action: :user, as: :user, user_id: /\d{,6}/
      get 'users/:user_id/drafts', action: :drafts, as: :drafts, user_id: /\d{,6}/
    end
  end
  resources :article_comments, only: [:create, :edit, :update, :destroy]

end

app/models/monthly_report.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: monthly_reports
#
#  id               :integer          not null, primary key
#  user_id          :integer          not null
#  target_month     :date             not null
#  shipped_at       :datetime
#  project_summary  :text
#  business_content :text
#  looking_back     :text
#  next_month_goals :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  comments_count   :integer          default(0), not null
#

class MonthlyReport < ApplicationRecord
  belongs_to :user
  has_many :comments, class_name: 'MonthlyReportComment', dependent: :delete_all
  has_many :likes, class_name: 'MonthlyReportLike', dependent: :delete_all
  has_many :monthly_report_tags, dependent: :destroy
  has_many :tags, through: :monthly_report_tags
  has_one :monthly_working_process, dependent: :destroy

  validates :user, presence: true
  validates :target_month, presence: true
  validates :project_summary, length: { maximum: 5000 }
  validates :business_content, length: { maximum: 5000 }
  validates :looking_back, length: { maximum: 5000 }
  validates :next_month_goals, length: { maximum: 5000 }
  validate :target_beginning_of_month?
  validate :target_month_registrable_term
  validate :uniq_by_user_and_target_month, on: :create
  with_options if: :shipped? do
    validates :project_summary, presence: true
    validates :business_content, presence: true
    validates :looking_back, presence: true
    validates :next_month_goals, presence: true
    validates :monthly_report_tags, presence: true
    validates :monthly_working_process, presence: true
  end

  validates_associated :monthly_report_tags

  scope :year, ->(year) { where(target_month: (Time.zone.local(year))..(Time.zone.local(year).end_of_year)) }
  scope :released, -> { where.not(shipped_at: nil) }
  scope :latest, -> { where(target_month: User.report_registrable_to.beginning_of_month) }

  def self.of_latest_month_registered_by(user)
    user.monthly_reports.find_by(target_month: User.report_registrable_to.beginning_of_month)
  end

  def registrable_term?
    return false unless user
    user.report_registrable_months.include? target_month
  end

  def prev_month
    return unless target_month
    self.class.find_by(user: user, target_month: target_month.prev_month)
  end

  def next_month
    return unless target_month
    self.class.find_by(user: user, target_month: target_month.next_month)
  end

  def this_month_goals
    prev_month.try!(:next_month_goals)
  end

  def set_prev_monthly_report!
    raise ActiveRecord::RecordNotFound unless prev_month
    contents = %w[project_summary business_content looking_back next_month_goals]
    assign_attributes(prev_month
                      .attributes
                      .select { |key, _| contents.include? key }
                      .merge('tags' => prev_month.tags,
                             'monthly_working_process' => prev_month.monthly_working_process))
    self
  end

  def shipped!
    self.shipped_at ||= Time.current
  end

  def shipped?
    shipped_at.present?
  end

  def related_users
    users = [user]
    users += comments.map(&:user)

    users.uniq
  end

  def browseable?(other_user)
    shipped? || user == other_user
  end

  def find_like_by_user(user)
    likes.find_by(user: user)
  end

  def self.target_month_select_options
    released_reports = MonthlyReport.released
    return [] if released_reports.blank?
    first_month = released_reports.minimum(:target_month)
    last_month = released_reports.maximum(:target_month)
    all_months(first_month, last_month).map { |month| [month.strftime('%Y年%m月'), month] }
  end

  def self.all_months(first_month, last_month)
    loop.each_with_object([first_month]) do |_, days|
      nm = days.last.next_month
      nm > last_month ? (break days) : days << nm
    end
  end

  private

  def target_month_registrable_term
    return if user.blank?
    return if target_month.blank?
    return if registrable_term?
    errors.add :target_month, ' must included by user.report_registrable_months'
  end

  def target_beginning_of_month?
    return if target_month.blank?
    return if target_month == target_month.beginning_of_month
    errors.add :target_month, 'invalid target month'
  end

  def uniq_by_user_and_target_month
    return if target_month.blank? || user.blank?
    return unless self.class.find_by(user: user, target_month: target_month)
    errors.add :target_month, 'report already registered'
  end
end

app/controllers/monthly_reports_controller.rb
# frozen_string_literal: true

class MonthlyReportsController < ApplicationController
  before_action :assign_saved_report, only: %i[edit update]

  def index
    references = [{ user: :groups }, :monthly_working_process, { monthly_report_tags: :tag }]
    @q = MonthlyReport.includes(references).ransack(search_params)
    @monthly_reports = @q.result(distinct: true).released.order('shipped_at desc').page params[:page]
  end

  def user
    @target_year = (params[:target_year] || User.report_registrable_to.year).to_i
    @report_user = User.find(params[:user_id])
    @monthly_reports = user_reports_in_year(@target_year, @report_user)
  end

  def show
    response.headers['Cache-Control'] = 'no-cache, no-store'
    references = [{ comments: { user: :user_profile } }, { likes: { user: :user_profile } }]
    @monthly_report = MonthlyReport.includes(references).find(params[:id])
    raise(Forbidden, 'can not see wip reports of other users') unless browseable?(@monthly_report)
  end

  def new
    target_month = params[:target_month] || User.report_registrable_to.beginning_of_month
    @monthly_report = current_user.monthly_reports.build(target_month: target_month)
  end

  def create
    @monthly_report = MonthlyReport.new(permitted_params) do |report|
      report.user   = current_user
      assign_relational_params(report)
    end
    shipped_at_was = @monthly_report.shipped_at_was
    if @monthly_report.save
      monthly_report_notify(shipped_at_was)
      redirect_to @monthly_report
    else
      flash_errors(@monthly_report)
      render :new
    end
  end

  def edit; end

  def update
    @monthly_report.assign_attributes(permitted_params)
    assign_relational_params(@monthly_report)
    shipped_at_was = @monthly_report.shipped_at_was

    if @monthly_report.save
      monthly_report_notify(shipped_at_was)
      redirect_to @monthly_report
    else
      flash_errors(@monthly_report)
      render :edit
    end
  end

  def copy
    @monthly_report = MonthlyReport.new(target_month: params[:target_month], user: current_user).set_prev_monthly_report!
    render :new
  end

  private

  def assign_saved_report
    @monthly_report = current_user.monthly_reports.includes(monthly_report_tags: :tag).find params[:id]
    @saved_shipped_at = @monthly_report.shipped_at
  end

  def browseable?(monthly_report)
    monthly_report.browseable?(current_user)
  end

  def flash_errors(monthly_report)
    flash.now[:error] = monthly_report.errors.full_messages
  end

  def assign_relational_params(report)
    report.shipped! unless params[:wip]
    report.monthly_working_process = working_processes(report)
    report.tags = monthly_report_tags
  end

  def working_processes(report)
    processes_params = Array(params[:working_process])
    process = report.monthly_working_process || MonthlyWorkingProcess.new(monthly_report: report)

    process.attributes = MonthlyWorkingProcess::PROCESSES.reduce({}) do |hash, key|
      value = processes_params.include?(key)
      hash.merge!(key => value)
    end

    process
  end

  def monthly_report_tags
    tags = params[:monthly_report][:monthly_report_tags].try!(:split, ',').try!(:map) do |name|
      tag = Tag.find_or_initialize_by_name_ignore_case(name.strip)
      tag.save ? tag : nil # 許容できないタグは無視
    end.try!(:compact)

    tags || []
  end

  def user_reports_in_year(year, report_user)
    reports = MonthlyReport.year(year).includes(:user).where(user: report_user)

    (1..12).map do |month|
      target_month = Date.new(year, month, 1)
      report = reports.find { |r| r.target_month == target_month }
      report ||= MonthlyReport.new(user: report_user, target_month: target_month)
      report.registrable_term? ? report : nil
    end.compact
  end

  def permitted_params
    params.require(:monthly_report).permit(
      :target_month,
      :project_summary,
      :business_content,
      :looking_back,
      :next_month_goals,
    )
  end

  def search_params
    return unless params[:q]
    params[:q][:tags_name_in] = params[:q][:tags_name_in]&.split(',')&.flatten

    search_conditions = [
      :user_groups_id_eq,
      :user_name_cont,
      :target_month_eq,
      tags_name_in: [],
    ].concat(process_conditions)

    params.require(:q).permit(search_conditions)
  end

  def process_conditions
    MonthlyWorkingProcess::PROCESSES.map do |process|
      "monthly_working_process_#{process}_eq".to_sym
    end
  end

  def monthly_report_notify(shipped_at_was)
    return if shipped_at_was.present? || params[:wip]
    Mailer::Notify.monthly_report_registration(current_user.id, @monthly_report.id).deliver_now
  end
end

app/views/monthly_reports/_comment.html.slim
.panel.panel-default id=("comment-#{comment.id}")
  .panel-heading.monthly-report-panel-header
    = link_to comment.user.name, user_profile_path(comment.user.user_profile), class: 'text-info' 
    = ' さんが '
    = link_to comment.updated_at, monthly_report_path(comment.monthly_report_id, anchor: "comment-#{comment.id}"), class: 'text-info'
    = ' にコメント '
    == render 'likes/like', likable: comment
    - if comment.user == current_user
      .pull-right
        = content_tag :a, href: monthly_report_comment_path(comment), class: 'monthly_report_comment_destroy text-muted', 'data-method' => :delete, 'data-confirm' => 'コメントを削除して宜しいですか？'
          span.glyphicon.glyphicon-remove aria-hidden="true"
      .pull-right
        = content_tag :div, class: :monthly_report_comment_edit, style: 'cursor: pointer'
          span.glyphicon.glyphicon-pencil aria-hidden="true" 　
          = hidden_field_tag :comment_id, comment.id
  .panel-body
    .markdown-view
      textarea.hidden = comment.comment
      .markdown-body

app/views/monthly_reports/_form.html.slim
.page-content.well
  - if params[:action] == 'new' && monthly_report.prev_month
    #prev_month_report_copy
      = link_to '先月の月報をコピー', { action: 'copy', target_month: monthly_report.target_month }, class: 'btn btn-default'

  = form_for monthly_report, html: { class: 'form-horizontal' } do |f|
    - placeholders = HelpText.placeholders(:monthly_report)
    - hints = HelpText.hints(:monthly_report)
    .form-group
      = f.label :target_month, class: 'control-label col-sm-3'
      .col-sm-9
        select#monthly_report_target_month.form-control onchange='location.href=this.selectedOptions[0].getAttribute("href")'
          - current_user.report_registrable_months.each do |m|
            - report = current_user.monthly_reports.find_or_initialize_by(target_month: m)
            - path = report.new_record? ? new_monthly_report_path(target_month: m) : edit_monthly_report_path(report)
            option value=(m) href=(path) selected=(true if monthly_report.target_month == m) = m.strftime('%Y年%m月')
    .form-group
      = f.label :project_summary, class: 'control-label col-sm-3'
      .col-sm-9
        == render 'layouts/markdown_editor', rows: 5, attr: :project_summary, form: f, placeholder: placeholders[:project_summary]
    .form-group
      = f.label :monthly_report_tags, class: 'control-label col-sm-3'
      .col-sm-9
        = f.hidden_field :monthly_report_tags, id: :monthly_report_tags_input, class: 'form-control'
        == render 'shared/tag_field', tags: monthly_report.monthly_report_tags.map(&:name), placeholder: placeholders[:tags], attr: 'monthly_report_tags'
    .form-group
      = f.label :monthly_working_process, class: 'control-label col-sm-3'
      .col-sm-9.btn-group data-toggle="buttons"
        - MonthlyWorkingProcess::PROCESSES.each do |process|
          - value = !!monthly_report.monthly_working_process.try!(process)
          label.btn.btn-default class=('active' if value)
            = check_box_tag "working_process[]", process, value, autocomplete: "off"
            span = t "activerecord.attributes.monthly_working_process.#{process}"
    .form-group
      = f.label :business_content, class: 'control-label col-sm-3'
      .col-sm-9
        == render 'layouts/markdown_editor', rows: 5, attr: :business_content, form: f, placeholder: placeholders[:business_content]
    .form-group
      = label_tag :this_month_goals, '今月の目標', class: 'control-label col-sm-3'
      .col-sm-9
        .form-control-static
          - this_month_goals = monthly_report.this_month_goals.presence || hints[:this_month_goals]
          = render 'layouts/markdown_view', content: this_month_goals
    .form-group
      = f.label :looking_back, class: 'control-label col-sm-3'
      .col-sm-9
        == render 'layouts/markdown_editor', rows: 5, attr: :looking_back, form: f, placeholder: placeholders[:looking_back]
    .form-group
      = f.label :next_month_goals, class: 'control-label col-sm-3'
      .col-sm-9
        == render 'layouts/markdown_editor', rows: 5, attr: :next_month_goals, form: f, placeholder: placeholders[:next_month_goals]
    = f.hidden_field :target_month
    - if @saved_shipped_at
      = f.button 'Update（月報を更新）', class: 'btn btn-lg btn-success btn-block'
    - else
      = f.button 'Save as WIP（下書き保存）', name: :wip, class: 'btn btn-lg btn-info btn-block'
      = f.button 'Ship（保存して公開）', class: 'btn btn-lg btn-success btn-block'

app/views/monthly_reports/_like.html.slim
- like = monthly_report.find_like_by_user(current_user)
.like-btn
  - if like
    = link_to 'いいね済み',
              monthly_report_like_path(monthly_report, like),
              class: 'btn btn-default',
              method: 'delete',
              role: 'button',
              remote: true
  - else
    = link_to 'いいね！',
              monthly_report_likes_path(monthly_report),
              class: 'btn btn-success',
              method: 'post',
              role: 'button',
              remote: true
.like-count
  strong = link_to monthly_report.likes_count, '', class: 'text-info', data: { toggle: 'modal', target: '#like-user-modal' }

#like-user-modal.modal.fade tabindex='-1'
  .modal-dialog.modal-sm
    .modal-content
      .modal-header-like
        h4.modal-title.text-center = "#{monthly_report.likes_count}人がいいね！と言っています"
      .modal-body
        .list-group
          - monthly_report.likes.order(:created_at).each do |like|
            = link_to like.user.name, like.user.user_profile, class: 'list-group-item'
      .modal-footer
        button.btn.btn-success data-dismiss='modal' 閉じる

app/views/monthly_reports/_new_comment.html.slim
.markdown-editor
  = form_for comment do |f|
    = f.hidden_field :monthly_report_id
    ul.nav.nav-tabs
      li.tab-md-write.active
        = link_to 'Write', "##{attr}-write", "data-toggle" => "tab", class: 'text-info'
      li.tab-md-preview
        = link_to 'Preview', "##{attr}-preview", "data-toggle" => "tab", class: 'text-info'
      li.pull-right
        = f.button 'Comment', class: 'btn btn-success'

    .tab-content.markdown-content
      .tab-pane.active id=("#{attr}-write")
          = f.text_area :comment, rows: 5, class: 'form-control', maxlength: 3000
          p
            a.text-info href='https://help.github.com/articles/basic-writing-and-formatting-syntax/' target='_blank' Markdown
            span = '記法が使えます。'
      .tab-pane.content-md-preview.markdown-body id=("#{attr}-preview")

app/views/monthly_reports/change_like_status.js.erb
$('#monthly-report-like-btn').html(
  "<%= j(render 'monthly_reports/like', monthly_report: @monthly_report) %>"
);

app/views/monthly_reports/edit.html.slim
- provide :page_title, "月報編集(#{@monthly_report.target_month.strftime('%Y年%m月')})"

== render 'monthly_reports/form', monthly_report: @monthly_report

app/views/monthly_reports/index.html.slim
- provide :page_title, "月報トップ"
- placeholders = HelpText.placeholders(:monthly_report)

.page-content
  .jumbotron
    .container
      = search_form_for @q, { class: 'form-horizontal' } do |f|
        .form-group
          = f.label :user_groups_id_eq, 'グループ', class: 'control-label col-xs-2'
          .col-xs-10
            = f.select :user_groups_id_eq, options_for_select(Group.active.pluck(:name, :id), selected: @q.user_groups_id_eq), { include_blank: true }, class: 'form-control'
        .form-group
          = f.label :user_name_cont, '氏名', class: 'control-label col-xs-2'
          .col-xs-10
            = f.search_field :user_name_cont, class: 'form-control'
        .form-group
          = f.label :target_month_eq, '対象月', class: 'control-label col-xs-2'
          .col-xs-10
            = f.select :target_month_eq, options_for_select(MonthlyReport.target_month_select_options, selected: @q.target_month_eq), { include_blank: true }, class: 'form-control'
        .form-group
          = f.label :tags_name_in, '使用した技術', class: 'control-label col-xs-2'
          .col-xs-10
            = f.hidden_field :tags_name_in, id: :monthly_report_tags_input, class: 'form-control'
            == render 'shared/tag_field', tags: @q.tags_name_in, placeholder: placeholders[:tags], attr: 'monthly_report_tags'
        .form-group
          = f.label :monthly_working_process, '担当した工程', class: 'control-label col-xs-2'
          .col-xs-10.btn-group.btn-group-sm data-toggle="buttons"
            - MonthlyWorkingProcess::PROCESSES.each do |process|
              - column = "monthly_working_process_#{process}_eq"
              label.btn.btn-default class=('active' if @q.send(column))
                = f.check_box column, { autocomplete: "off" }, true, nil
                span = t "activerecord.attributes.monthly_working_process.#{process}"
        .form-group
          .col-xs-10.col-xs-offset-2
            = f.button '検索', class: 'btn btn-default'
.page-content
  h3 = @q.conditions.empty? ? '最新の月報一覧' : '検索結果'
  #report_index
    == render partial: 'layouts/report_index', locals: { monthly_reports: @monthly_reports }
  = paginate @monthly_reports

app/views/monthly_reports/new.html.slim
- provide :page_title, "月報登録"

== render 'monthly_reports/form', monthly_report: @monthly_report

app/views/monthly_reports/show.html.slim
- provide :page_title,  (link_to @monthly_report.user.name, user_profile_path(@monthly_report.user.user_profile), class: 'text-profile-link')

.panel-group
  .panel.panel-default
    .panel-heading.monthly-report-panel-header
      .panel-title.row
        .col-xs-2
          - if @monthly_report.prev_month.try(:browseable?, current_user)
            a.btn.btn-default.btn-xs.monthly-report-panel-button href=(monthly_report_path(@monthly_report.prev_month)) role="button" 先月
        .col-xs-8.monthly-report-panel-date
          - if @monthly_report.shipped?
            span.label.label-success.monthly-report-status 登録済
          -else
            span.label.label-info.monthly-report-status 下書き
          = "#{@monthly_report.target_month.strftime("%Y年%m月")}の月報"
        .col-xs-2
          - if @monthly_report.next_month.try(:browseable?, current_user)
            a.btn.btn-default.btn-xs.monthly-report-panel-button.pull-right href=(monthly_report_path(@monthly_report.next_month)) role="button" 来月
    .panel-body
      form.form-horizontal
        - attr = 'activerecord.attributes.monthly_report'
        .form-group
          label.col-sm-3.control-label = t "#{attr}.project_summary"
          .col-sm-9.form-control-static
            = render 'layouts/markdown_view', content: @monthly_report.project_summary
        .form-group
          label.col-sm-3.control-label = t "#{attr}.monthly_report_tags"
          .col-sm-9.form-control-static
            = render 'shared/tags', tags: @monthly_report.tags, prefix: :report
        .form-group
          - process_attr = 'activerecord.attributes.monthly_working_process'
          label.col-sm-3.control-label = t "#{attr}.monthly_working_process"
          .col-sm-9.form-control-static.btn-group
            - @monthly_report.monthly_working_process.processes.select.each do |key, value|
              - next unless value
              - url = monthly_reports_path("q[monthly_working_process_#{key}_eq]" => true)
              a.btn.btn-default href=(url) = t "#{process_attr}.#{key}"
        .form-group
          label.col-sm-3.control-label = t "#{attr}.business_content"
          .col-sm-9.form-control-static
            = render 'layouts/markdown_view', content: @monthly_report.business_content
        .form-group
          label.col-sm-3.control-label 今月の目標
          .col-sm-9.form-control-static
            = render 'layouts/markdown_view', content: @monthly_report.this_month_goals
        .form-group
          label.col-sm-3.control-label = t "#{attr}.looking_back"
          .col-sm-9.form-control-static
            = render 'layouts/markdown_view', content: @monthly_report.looking_back
        .form-group
          label.col-sm-3.control-label = t "#{attr}.next_month_goals"
          .col-sm-9.form-control-static
            = render 'layouts/markdown_view', content: @monthly_report.next_month_goals

#monthly-report-like-btn
  == render 'monthly_reports/like', monthly_report: @monthly_report

- if @monthly_report.user == current_user
  = link_to '編集',
            edit_monthly_report_path(@monthly_report),
            class: 'btn btn-success btn-lg btn-block',
            role: 'button'

- if @monthly_report.shipped?
  h2 コメント
  - @monthly_report.comments.order(:created_at).each do |comment|
    == render 'monthly_reports/comment', comment: comment

  == render 'shared/new_comment', comment: @monthly_report.comments.new, attr: 'new-comment', hidden: :monthly_report_id

app/views/monthly_reports/user.html.slim
- provide :page_title, (link_to @report_user.name, user_profile_path(@report_user.user_profile), class: 'text-profile-link')

.page-content
  h3 = "#{@target_year}年の月報"
  - next_year = @target_year + 1
  - prev_year = @target_year - 1
  = link_to "<< #{prev_year}年", user_monthly_reports_path(@report_user, target_year: prev_year), class: 'text-info'
  = link_to "#{next_year}年 >>", user_monthly_reports_path(@report_user, target_year: next_year), class: 'pull-right text-info'
  #report_index
    table.table
      thead
        tr
          th 対象月
          th ステータス
          th リンク
      tbody
        - @monthly_reports.each do |report|
          - if @report_user == current_user
            == render partial: 'layouts/my_report', locals: { report: report }
          - else
            == render partial: 'layouts/user_report', locals: { report: report }