config/routes.rb
require_relative 'routes/constraints'

Rails.application.routes.draw do

  devise_for :users, skip: [:sessions, :password]
  devise_scope :user do
    resources :sessions, only: [:new, :create] do
      collection do
        delete 'destroy', as: :destroy
        get 'password_reset', as: :password_reset
      end
    end
    resources :password_resets, only: [:new, :create, :edit, :update]
  end

  begin
    ActiveAdmin.routes(self)
  rescue ActiveAdmin::DatabaseHitDuringLoad => e
    puts "#{e.class} has occurred."
  end

  resources :inquiries, only: [:create]
  resources :groups, only: [:index]
  resources :monthly_report_comments, only: [:create, :edit, :update, :destroy]

  root to: 'root#index'

  resources :announcements, only: [:index]
  resources :user_profiles, only: [:show, :edit, :update]
  resources 'monthly_reports', except: :destroy, constraints: Constraints::PageCount do
    resources :monthly_report_likes, only: [:create, :destroy], as: 'likes'
    collection do
      get 'users/:user_id', action: :user, as: :user, user_id: /\d{,6}/, constraints: Constraints::TargetYear
      get :copy
    end
  end

  resources :articles, constraints: Constraints::PageCount do
    collection do
      get 'users/:user_id', action: :user, as: :user, user_id: /\d{,6}/
      get 'users/:user_id/drafts', action: :drafts, as: :drafts, user_id: /\d{,6}/
    end
  end
  resources :article_comments, only: [:create, :edit, :update, :destroy]

end

app/models/user_profile.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: user_profiles
#
#  id                :integer          not null, primary key
#  user_id           :integer          not null
#  self_introduction :text
#  blood_type        :integer          default("blood_blank"), not null
#  birthday          :date
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class UserProfile < ApplicationRecord
  belongs_to :user

  validates :self_introduction, length: { maximum: 1000 }
  validates :blood_type, presence: true

  enum blood_type: { blood_blank: 0, a: 1, b: 2, ab: 3, o: 4 }
end

app/controllers/user_profiles_controller.rb
# frozen_string_literal: true

class UserProfilesController < ApplicationController
  def show
    @profile = UserProfile.find(params[:id])
  end

  def edit
    @profile = UserProfile.find_by!(id: params[:id], user: current_user)
  end

  def update
    @profile = UserProfile.find_by!(id: params[:id], user: current_user)
    @profile.assign_attributes valid_profile_params
    if @profile.save
      redirect_to @profile
    else
      flash.now[:error] = @profile.errors.full_messages
      render :edit
    end
  end

  private

  def permitted_params
    params.require(:user_profile)
          .permit(:self_introduction, :blood_type, :birthday)
  end

  def valid_profile_params
    return permitted_params if UserProfile.blood_types.include? permitted_params[:blood_type]
    permitted_params.reject { |key, _| key == 'blood_type' }
  end
end

app/views/user_profiles/_form.html.slim
.page-content.well
  h2
    span.glyphicon.glyphicon-user
    span  #{profile.user.name}

  = form_for profile, html: { class: 'form-horizontal' } do |f|
    .form-group
      = f.label :blood_type, class: 'col-sm-2 control-label'
      .col-sm-10.btn-group data-toggle='buttons'
        - UserProfile.blood_types_i18n.each do |key, label|
          = f.label "blood_type_#{key}", class: "btn btn-default #{'active' if profile.blood_type == key}"
            = f.radio_button :blood_type, key
            = label

    .form-group
      = f.label :birthday, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :birthday, class: 'form-control'

    .form-group
      = f.label :interested_topics, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.hidden_field :interested_topics, id: :interested_topics_input, class: 'form-control'
        == render 'shared/tag_field', tags: profile.interested_topics.map(&:name), placeholder: '例） Java + <Enter>', attr: :interested_topics

    .form-group
      = f.label :self_introduction, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_area :self_introduction, class: 'form-control'

    = button_tag '登録', class: 'btn btn-lg btn-success btn-block'

app/views/user_profiles/edit.html.slim
- provide :page_title, 'プロフィール編集'

== render partial: 'form', locals: { profile: @profile }

app/views/user_profiles/index.html.slim
- provide :page_title, "プロフィールトップ"
- placeholders = HelpText.placeholders(:user_profile)

.page-content
  .jumbotron
    .container
      = search_form_for @q, { class: 'form-horizontal' } do |f|
        .form-group
          = f.label :user_name_cont, '氏名', class: 'control-label col-xs-2'
          .col-xs-10
            = f.search_field :user_name_cont, class: 'form-control'
        .form-group
          = f.label :self_introduction_cont, '自己紹介', class: 'control-label col-xs-2'
          .col-xs-10
            = f.search_field :self_introduction_cont, class: 'form-control'
        .form-group
          = f.label :user_entry_date_gteq, '入社日', class: 'control-label col-xs-2'
          .col-xs-2.user-entry-date-select-form
            = select_tag "entry_year_start",
                options_for_select(User.entry_year_select_options, selected: @q.user_entry_date_gteq.try(:year)),
                { include_blank: true , class: 'form-control' }
          .col-xs-1.control-label.user-entry-date-description = "年"
          .col-xs-2.user-entry-date-select-form
            = select_tag "entry_month_start",
                options_for_select(User.entry_month_select_options, selected: @q.user_entry_date_gteq.try(:month)),
                { include_blank: true , class: 'form-control' }
          .col-xs-1.control-label.user-entry-date-description = "月"
          .col-xs-1.control-label.user-entry-date-description = "から"
        .form-group
          .col-xs-2
          .col-xs-2.user-entry-date-select-form
            = select_tag "entry_year_end",
                options_for_select(User.entry_year_select_options, selected: @q.user_entry_date_lteq.try(:year)),
                { include_blank: true , class: 'form-control' }
          .col-xs-1.control-label.user-entry-date-description = "年"
          .col-xs-2.user-entry-date-select-form
            = select_tag "entry_month_end",
                options_for_select(User.entry_month_select_options, selected: @q.user_entry_date_lteq.try(:month)),
                { include_blank: true , class: 'form-control' }
          .col-xs-1.control-label.user-entry-date-description = "月"
          .col-xs-1.control-label.user-entry-date-description = "まで"
        .form-group
          .col-xs-10.col-xs-offset-2
            = f.button '検索', class: 'btn btn-default'
.page-content
  h3 = @q.conditions.empty? ? 'プロフィール一覧' : '検索結果'
  #report_index
    == render partial: 'layouts/user_profile_index', locals: { user_profiles: @user_profiles }
  = paginate @user_profiles

app/views/user_profiles/new.html.slim
- provide :page_title, 'プロフィール登録'

== render partial: 'form', locals: { profile: @profile }

app/views/user_profiles/show.html.slim
- provide :page_title, 'プロフィール'

.page-content
  .jumbotron
    section
      h2.profile-heading
        span.glyphicon.glyphicon-user
        span
          = @profile.user.name
      - if current_user == @profile.user
        .edit-profile
          = link_to('プロフィール編集', edit_user_profile_path(@profile), class: 'text-info')
      = link_to 'このユーザーの月報を閲覧', user_monthly_reports_path(@profile.user), class: 'pull-right text-info'
      table.table
        tbody
          tr
            th グループ
            td 
              = @profile.user.groups.map { |g| "【#{g.name}】" }.join
          tr
            th 社員番号
            td
              = @profile.user.employee_code
          tr
            th メールアドレス
            td
              = @profile.user.email
          tr
            th 入社日
            td
              = @profile.user.entry_date
          tr
            th 性別
            td
              = @profile.user.gender_i18n
          tr
            th 血液型
            td
              = @profile.blood_type_i18n
          tr
            th 誕生日
            td
              = @profile.birthday || '未入力'
          tr
            th 興味のある技術
            td
              = render 'shared/tags', tags: @profile.tags, prefix: :interested
    section
      h2.profile-heading 自己紹介
      pre
        = @profile.self_introduction.presence || '未入力'