config/routes.rb
require_relative 'routes/constraints'

Rails.application.routes.draw do

  devise_for :users, skip: [:sessions, :password]
  devise_scope :user do
    resources :sessions, only: [:new, :create] do
      collection do
        delete 'destroy', as: :destroy
        get 'password_reset', as: :password_reset
      end
    end
    resources :password_resets, only: [:new, :create, :edit, :update]
  end

  begin
    ActiveAdmin.routes(self)
  rescue ActiveAdmin::DatabaseHitDuringLoad => e
    puts "#{e.class} has occurred."
  end

  resources :inquiries, only: [:create]
  resources :groups, only: [:index]
  resources :monthly_report_comments, only: [:create, :edit, :update, :destroy]

  root to: 'root#index'

  resources :announcements, only: [:index]
  resources :user_profiles, only: [:show, :edit, :update]
  resources 'monthly_reports', except: :destroy, constraints: Constraints::PageCount do
    resources :monthly_report_likes, only: [:create, :destroy], as: 'likes'
    collection do
      get 'users/:user_id', action: :user, as: :user, user_id: /\d{,6}/, constraints: Constraints::TargetYear
      get :copy
    end
  end

  resources :articles, constraints: Constraints::PageCount do
    collection do
      get 'users/:user_id', action: :user, as: :user, user_id: /\d{,6}/
      get 'users/:user_id/drafts', action: :drafts, as: :drafts, user_id: /\d{,6}/
    end
  end
  resources :article_comments, only: [:create, :edit, :update, :destroy]

end

app/controllers/root_controller.rb
# frozen_string_literal: true

class RootController < ApplicationController
  def index
    references = [{ user: :groups }, :monthly_working_process, { monthly_report_tags: :tag }]
    @monthly_reports = MonthlyReport.includes(references).latest.released.order('shipped_at desc').first(5)
    @announcements = Announcement.published.first(5)
  end
end

app/views/root/index.html.slim
.page-content.clearfix
  h3 お知らせ
  #announcement_index
    == render partial: 'layouts/announcement_index', locals: { announcements: @announcements }
    = link_to 'お知らせ一覧はこちら', announcements_path, class: 'pull-right text-info'

.page-content.clearfix
  h3 最近投稿された月報
  #report_index
    == render partial: 'layouts/report_index', locals: { monthly_reports: @monthly_reports }
    = link_to '月報一覧はこちら', monthly_reports_path, class: 'pull-right text-info'